config:
  redis_subnet_cidr_prefix: 28
  redis_subnet_public_ip: false

  redis_user: redis
  redis_group: redis
  redis_sentinel_group: redis-sentinel

  redis_db_port: 6379
  redis_sentinel_port: 26379

  redis_password: "%%redis_password:30"
  redis_sentinel_password: "%%redis_sentinel_password:30"

  redis_data_dir: /var/lib/redis
